### ISSUE TITLE
Typelevel weaver TODO-list 

### ISSUE THREAD

**Issue by Baccata** [typelevel/weaver-test#1]
This issue tracks the things to do to "move" Weaver over to the Typelevel organisation (see the governance issue [here](https://github.com/typelevel/governance/issues/114/)). 

- [ ] Add the code of conduct
- [ ] Update the directory structure (which was originally coming from mill) and the build to use the Typelevel SBT plugin
- [ ] Get rid of the specs2-interop module 
- [ ] Set-up CI / publishing
- [ ] Make the fork orphan via a request to gh (https://support.github.com/request/fork)
- [ ] Copy the issues over from the Disney repo
- [ ] Work on a couple breaking changes (in particular how expect.same  and expect.eql work)
- [ ] Remove mentions of Disney wherever relevant (including the Disney logo that appears on the website)
- [ ] Issue a 0.9.0 release
- [ ] Update Disney weaver's default branch to nothing but a README pointing to the TL weaver.

**Comment by lorandszakacs** [comment]
Writing here for visibility.

When the time comes, issues can be copied over using this scala-cli script:
https://github.com/lorandszakacs/gh-issues-copy

Assuming scala-cli and github cli installed, it's should just be a simple:
```
./gh-issues-copy.scala -- disneystreaming/weaver-test typelevel/weaver-test 40
```

Samples of how copying looks like can be found here:
https://github.com/lorandszakacs/test-target/issues

**Comment by zainab-ali** [comment]
As well as the changes in the checklist above, we've decided to include #64 to simplify the `expect` macro.

**Comment by zainab-ali** [comment]
When the time comes, we can migrate users with Scala Steward by PRing [this change](https://github.com/scala-steward-org/scala-steward/compare/main...zainab-ali:scala-steward:weaver-typelevel) to the Scala Steward repo. 

We can also prompt them to use scalafix for code changes: here are some [example migration notes](https://gist.github.com/zainab-ali/f3f29a5f629ec0a6bf7706664ea98ffe).

**Comment by zainab-ali** [comment]
The open issues have been copied over from disneystreaming. Thanks @lorandszakacs for the script!

**Comment by Baccata** [comment]
I'm still waiting on some legal information that will hopefully allow the project to transition the to the standard apache2 license. It would be preferable for this to happen before the first TL release.

**Comment by zainab-ali** [comment]
For reference, https://github.com/typelevel/governance/issues/114 tracks the current state of the Apache 2 license transition.

**Comment by zainab-ali** [comment]
The license has been transitioned in https://github.com/typelevel/weaver-test/pull/150 and weaver `0.9.0` has been [released](https://github.com/typelevel/weaver-test/releases/tag/v0.9.0).

The [Scala steward PR](https://github.com/scala-steward-org/scala-steward/pull/3646) should move everyone over.

Thank you @Baccata !
